### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by keljoundi** [keljoundi/jquery-autocomplete#1]
- [ ]  remove query "class variable"
- [ ] combine two options properties for sorting
- [ ]  styling
- [ ] set default sourceComparitor = sourceDisplay property
- [ ]  implement container option
